machine: machine.packages.nixpkgs.buildFHSUserEnvBubblewrap {
  name = "timedoctor";
  # DEBUG=true ELECTRON_ENABLE_LOGGING=true I18NEXT_LNG=en
  runScript = "appimage-exec.sh -w ${machine.packages.timedoctorExtracted}";
  targetPkgs = _: [
    machine.packages.nixpkgs.alsaLib
    machine.packages.nixpkgs.appimageTools.appimage-exec
    machine.packages.nixpkgs.atk
    machine.packages.nixpkgs.at-spi2-atk
    machine.packages.nixpkgs.at-spi2-core
    machine.packages.nixpkgs.cairo
    machine.packages.nixpkgs.coreutils
    machine.packages.nixpkgs.cups
    machine.packages.nixpkgs.dbus
    machine.packages.nixpkgs.dbus.lib
    machine.packages.nixpkgs.desktop-file-utils
    machine.packages.nixpkgs.expat
    machine.packages.nixpkgs.expat.dev
    machine.packages.nixpkgs.file
    machine.packages.nixpkgs.freetype
    machine.packages.nixpkgs.gcc
    machine.packages.nixpkgs.gcc-unwrapped.lib
    machine.packages.nixpkgs.gdb
    machine.packages.nixpkgs.gdk-pixbuf
    machine.packages.nixpkgs.git
    machine.packages.nixpkgs.glib
    machine.packages.nixpkgs.glibc
    machine.packages.nixpkgs.gnome.gdk_pixbuf
    machine.packages.nixpkgs.gnome.gtk
    machine.packages.nixpkgs.gnome.gtk.dev
    machine.packages.nixpkgs.gnome.zenity
    machine.packages.nixpkgs.gnome2.GConf
    machine.packages.nixpkgs.gnumake
    machine.packages.nixpkgs.gnutar
    machine.packages.nixpkgs.gpsd
    machine.packages.nixpkgs.gtk3
    machine.packages.nixpkgs.gtk3.dev
    machine.packages.nixpkgs.gtk3-x11
    machine.packages.nixpkgs.gtk3-x11.dev
    machine.packages.nixpkgs.kdialog
    machine.packages.nixpkgs.libappindicator-gtk2.out
    machine.packages.nixpkgs.libexif
    machine.packages.nixpkgs.libjpeg8.out
    machine.packages.nixpkgs.libnotify
    machine.packages.nixpkgs.libpng
    machine.packages.nixpkgs.libxml2
    machine.packages.nixpkgs.libxslt
    machine.packages.nixpkgs.netcat
    machine.packages.nixpkgs.nettools
    machine.packages.nixpkgs.nodePackages.asar
    machine.packages.nixpkgs.nspr
    machine.packages.nixpkgs.nss
    machine.packages.nixpkgs.openjdk
    machine.packages.nixpkgs.pango
    machine.packages.nixpkgs.patchelf
    machine.packages.nixpkgs.python38
    machine.packages.nixpkgs.strace
    machine.packages.nixpkgs.sqlite
    machine.packages.nixpkgs.sqlite.dev
    machine.packages.nixpkgs.udev
    machine.packages.nixpkgs.unzip
    machine.packages.nixpkgs.utillinux
    machine.packages.nixpkgs.watch
    machine.packages.nixpkgs.wget
    machine.packages.nixpkgs.which
    machine.packages.nixpkgs.wrapGAppsHook
    machine.packages.nixpkgs.xdg_utils
    machine.packages.nixpkgs.xorg.libX11
    machine.packages.nixpkgs.xorg.libXau
    machine.packages.nixpkgs.xorg.libXaw
    machine.packages.nixpkgs.xorg.libXaw3d
    machine.packages.nixpkgs.xorg.libxcb
    machine.packages.nixpkgs.xorg.libXcomposite
    machine.packages.nixpkgs.xorg.libXcursor
    machine.packages.nixpkgs.xorg.libXdamage
    machine.packages.nixpkgs.xorg.libXdmcp
    machine.packages.nixpkgs.xorg.libXext
    machine.packages.nixpkgs.xorg.libXfixes
    machine.packages.nixpkgs.xorg.libXfont
    machine.packages.nixpkgs.xorg.libXfont2
    machine.packages.nixpkgs.xorg.libXft
    machine.packages.nixpkgs.xorg.libXi
    machine.packages.nixpkgs.xorg.libXinerama
    machine.packages.nixpkgs.xorg.libXmu
    machine.packages.nixpkgs.xorg.libXp
    machine.packages.nixpkgs.xorg.libXpm
    machine.packages.nixpkgs.xorg.libXpresent
    machine.packages.nixpkgs.xorg.libXrandr
    machine.packages.nixpkgs.xorg.libXrender
    machine.packages.nixpkgs.xorg.libXres
    machine.packages.nixpkgs.xorg.libXScrnSaver
    machine.packages.nixpkgs.xorg.libXt
    machine.packages.nixpkgs.xorg.libXTrap
    machine.packages.nixpkgs.xorg.libXtst
    machine.packages.nixpkgs.xorg.libXv
    machine.packages.nixpkgs.xorg.libXvMC
    machine.packages.nixpkgs.xorg.libXxf86dga
    machine.packages.nixpkgs.xorg.libXxf86misc
    machine.packages.nixpkgs.xorg.libXxf86vm
    machine.packages.nixpkgs.xorg.xcbutilkeysyms
    machine.packages.nixpkgs.zip
    machine.packages.nixpkgs.zlib
    machine.packages.nixpkgs.zsh
  ];
}
