#! /bin/sh -eu

nix \
  --extra-experimental-features flakes \
  --extra-experimental-features nix-command \
  --verbose \
  build \
  --print-build-logs \
  .#nixosConfigurations.machine.config.system.build.toplevel
