[isort]
atomic = true
combine_as_imports = true
force_alphabetical_sort = true
force_grid_wrap = 1
force_sort_within_sections = true
include_trailing_comma = true
remove_redundant_aliases = true
skip_gitignore = true
use_parentheses = true
multi_line_output = 3
