combine_control_expr = false
edition = "2021"
enum_discrim_align_threshold = 999
error_on_unformatted = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Item"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
reorder_impl_items = true
struct_field_align_threshold = 0
trailing_comma = "Vertical"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
version = "Two"
wrap_comments = true
