machine: [
  machine.packages.nixpkgs.acpi
  machine.packages.nixpkgs.age
  machine.packages.nixpkgs.awscli
  machine.packages.nixpkgs.beep
  machine.packages.nixpkgs.bind
  machine.packages.nixpkgs.binutils
  machine.packages.nixpkgs.black
  machine.packages.nixpkgs.burpsuite
  machine.packages.nixpkgs.cabal-install
  machine.packages.nixpkgs.cargo
  machine.packages.nixpkgs.coreutils
  machine.packages.nixpkgs.curl
  machine.packages.nixpkgs.diction
  machine.packages.nixpkgs.diffoscope
  machine.packages.nixpkgs.evtest
  machine.packages.nixpkgs.gcc
  machine.packages.nixpkgs.ghc
  machine.packages.nixpkgs.gimp
  machine.packages.nixpkgs.git-sizer
  machine.packages.nixpkgs.gnumake
  machine.packages.nixpkgs.google-chrome
  machine.packages.nixpkgs.gptfdisk
  machine.packages.nixpkgs.hugo
  machine.packages.nixpkgs.inxi
  machine.packages.nixpkgs.kubectl
  machine.packages.nixpkgs.libreoffice
  machine.packages.nixpkgs.lshw
  machine.packages.nixpkgs.lsof
  machine.packages.nixpkgs.maven
  machine.packages.nixpkgs.mypy
  machine.packages.nixpkgs.ngrok
  machine.packages.nixpkgs.niv
  machine.packages.nixpkgs.nix-index
  machine.packages.nixpkgs.nixops
  machine.packages.nixpkgs.nixpkgs-fmt
  machine.packages.nixpkgs.nixpkgs-review
  machine.packages.nixpkgs.nodejs
  machine.packages.nixpkgs.nodePackages.asar
  machine.packages.nixpkgs.openjdk
  machine.packages.nixpkgs.optipng
  machine.packages.nixpkgs.parallel
  machine.packages.nixpkgs.parted
  machine.packages.nixpkgs.patchelf
  machine.packages.nixpkgs.pciutils
  machine.packages.nixpkgs.pcre
  machine.packages.nixpkgs.peek
  machine.packages.nixpkgs.python38
  machine.packages.nixpkgs.python38Packages.isort
  machine.packages.nixpkgs.qemu
  machine.packages.nixpkgs.shadow
  machine.packages.nixpkgs.shfmt
  machine.packages.nixpkgs.sops
  machine.packages.nixpkgs.terraform
  machine.packages.nixpkgs.tokei
  machine.packages.nixpkgs.tor
  machine.packages.nixpkgs.torbrowser
  machine.packages.nixpkgs.traceroute
  machine.packages.nixpkgs.tree
  machine.packages.nixpkgs.vlc
  machine.packages.nixpkgs.xclip
  machine.packages.nixpkgs.yq
]
