_: with _; [
  abs.editor.package
  inputs.nixpkgs.coreutils
  inputs.nixpkgs.curl
  inputs.nixpkgs.gnumake
  inputs.nixpkgs.google-chrome
  inputs.nixpkgs.gnupg
  inputs.nixpkgs.just
  inputs.nixpkgs.libreoffice
  inputs.nixpkgs.nixpkgs-fmt
  inputs.nixpkgs.parted
  inputs.nixpkgs.patchelf
  inputs.nixpkgs.peek
  inputs.nixpkgs.shadow
  inputs.nixpkgs.shfmt
  inputs.nixpkgs.tree
  inputs.nixpkgs.vlc
  inputs.nixpkgs.xclip
  inputs.nixpkgs.xdotool
]
