_: with _;
packages.nixpkgs.buildFHSUserEnvBubblewrap {
  name = "timedoctor";
  # DEBUG=true ELECTRON_ENABLE_LOGGING=true I18NEXT_LNG=en
  runScript = "appimage-exec.sh -w ${packages.timedoctorExtracted}";
  targetPkgs = _: [
    packages.nixpkgs.alsaLib
    packages.nixpkgs.appimageTools.appimage-exec
    packages.nixpkgs.atk
    packages.nixpkgs.at-spi2-atk
    packages.nixpkgs.at-spi2-core
    packages.nixpkgs.cairo
    packages.nixpkgs.coreutils
    packages.nixpkgs.cups
    packages.nixpkgs.dbus
    packages.nixpkgs.dbus.lib
    packages.nixpkgs.desktop-file-utils
    packages.nixpkgs.expat
    packages.nixpkgs.expat.dev
    packages.nixpkgs.file
    packages.nixpkgs.freetype
    packages.nixpkgs.gcc
    packages.nixpkgs.gcc-unwrapped.lib
    packages.nixpkgs.gdb
    packages.nixpkgs.gdk-pixbuf
    packages.nixpkgs.git
    packages.nixpkgs.glib
    packages.nixpkgs.glibc
    packages.nixpkgs.gnome.gdk_pixbuf
    packages.nixpkgs.gnome.gtk
    packages.nixpkgs.gnome.gtk.dev
    packages.nixpkgs.gnome.zenity
    packages.nixpkgs.gnome2.GConf
    packages.nixpkgs.gnumake
    packages.nixpkgs.gnutar
    packages.nixpkgs.gpsd
    packages.nixpkgs.gtk3
    packages.nixpkgs.gtk3.dev
    packages.nixpkgs.gtk3-x11
    packages.nixpkgs.gtk3-x11.dev
    packages.nixpkgs.kdialog
    packages.nixpkgs.libappindicator-gtk2.out
    packages.nixpkgs.libexif
    packages.nixpkgs.libjpeg8.out
    packages.nixpkgs.libnotify
    packages.nixpkgs.libpng
    packages.nixpkgs.libxml2
    packages.nixpkgs.libxslt
    packages.nixpkgs.netcat
    packages.nixpkgs.nettools
    packages.nixpkgs.nodePackages.asar
    packages.nixpkgs.nspr
    packages.nixpkgs.nss
    packages.nixpkgs.openjdk
    packages.nixpkgs.pango
    packages.nixpkgs.patchelf
    packages.nixpkgs.python38
    packages.nixpkgs.strace
    packages.nixpkgs.sqlite
    packages.nixpkgs.sqlite.dev
    packages.nixpkgs.udev
    packages.nixpkgs.unzip
    packages.nixpkgs.utillinux
    packages.nixpkgs.watch
    packages.nixpkgs.wget
    packages.nixpkgs.which
    packages.nixpkgs.wrapGAppsHook
    packages.nixpkgs.xdg_utils
    packages.nixpkgs.xorg.libX11
    packages.nixpkgs.xorg.libXau
    packages.nixpkgs.xorg.libXaw
    packages.nixpkgs.xorg.libXaw3d
    packages.nixpkgs.xorg.libxcb
    packages.nixpkgs.xorg.libXcomposite
    packages.nixpkgs.xorg.libXcursor
    packages.nixpkgs.xorg.libXdamage
    packages.nixpkgs.xorg.libXdmcp
    packages.nixpkgs.xorg.libXext
    packages.nixpkgs.xorg.libXfixes
    packages.nixpkgs.xorg.libXfont
    packages.nixpkgs.xorg.libXfont2
    packages.nixpkgs.xorg.libXft
    packages.nixpkgs.xorg.libXi
    packages.nixpkgs.xorg.libXinerama
    packages.nixpkgs.xorg.libXmu
    packages.nixpkgs.xorg.libXp
    packages.nixpkgs.xorg.libXpm
    packages.nixpkgs.xorg.libXpresent
    packages.nixpkgs.xorg.libXrandr
    packages.nixpkgs.xorg.libXrender
    packages.nixpkgs.xorg.libXres
    packages.nixpkgs.xorg.libXScrnSaver
    packages.nixpkgs.xorg.libXt
    packages.nixpkgs.xorg.libXTrap
    packages.nixpkgs.xorg.libXtst
    packages.nixpkgs.xorg.libXv
    packages.nixpkgs.xorg.libXvMC
    packages.nixpkgs.xorg.libXxf86dga
    packages.nixpkgs.xorg.libXxf86misc
    packages.nixpkgs.xorg.libXxf86vm
    packages.nixpkgs.xorg.xcbutilkeysyms
    packages.nixpkgs.zip
    packages.nixpkgs.zlib
    packages.nixpkgs.zsh
  ];
}
