# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9c68541d-ba2d-4475-a867-789580ecc1c4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/00ea7072-60ec-45cd-8421-5ebcfc977220";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c0f41e03-4fc2-439c-8816-52039fc252e0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptnix".device = "/dev/disk/by-uuid/3c60f0a3-4b24-4df5-bd5a-5edf6f136c3e";

  fileSystems."/nix/store" =
    { device = "/nix/store";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F446-8957";
      fsType = "vfat";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/eab6f133-4ac5-4856-870b-f26531a788db";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptdata".device = "/dev/disk/by-uuid/6a941b1f-6330-41e4-bf04-17a816aaee48";

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
