blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
edition = "2021"
enum_discrim_align_threshold = 80
error_on_line_overflow = true
error_on_unformatted = true
fn_args_layout = "Vertical"
fn_single_line = false
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 80
trailing_comma = "Vertical"
unstable_features = true
use_small_heuristics = "Max"
use_try_shorthand = false
version = "Two"
where_single_line = false
