blank_lines_upper_bound = 1
control_brace_style = "ClosingNextLine"
edition = "2018"
enum_discrim_align_threshold = 80
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "One"
imports_indent = "Block"
imports_layout = "Vertical"
match_arm_leading_pipes = true
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 80
unstable_features = true
use_small_heuristics = "Max"
use_try_shorthand = false
version = "Two"
