# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/95bbcdd7-b71c-4ebf-9f9b-3d5f9d08e751";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/34697849-d731-4e93-85ee-023bf33c9c6a";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a4af5753-2351-4dce-b963-d34438aae330";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."cryptnix".device = "/dev/disk/by-uuid/1027006c-a308-4ed0-a9c4-efeab1610619";

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/be0f0ce0-944d-4f9d-8ff5-cb22db4543a2";
    fsType = "ext4";
    neededForBoot = true;
  };

  boot.initrd.luks.devices."cryptdata".device = "/dev/disk/by-uuid/51ef0c8e-2671-4df1-bf92-3f2e1a868a26";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4C65-F8B4";
    fsType = "vfat";
  };

  swapDevices = [];

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
